FROM python:3.11

RUN apt-get update && apt-get install -y cron

WORKDIR /app
COPY . .

RUN pip install jwt
RUN pip install --no-cache-dir -r requirements.txt

#COPY crontabFile /etc/cron.d/cronfile
#RUN chmod 0644 /etc/cron.d/cronfile

RUN crontab -l | { cat; echo "* * * * * /usr/local/bin/python /app/historyUpdate.py >> /var/log/cron.log 2>&1"; } | crontab -

CMD ["sh", "-c", "cron && python app.py"]